### ISSUE TITLE
Support for Ghidra 10.3

### ISSUE THREAD

**Issue by blazkowolf** [zeroKilo/N64LoaderWV#23]
I'm not sure the effort involved to release a new version compatible with the latest Ghidra release (10.3). If your time does not allow, I totally understand.

**Comment by zeroKilo** [comment]
sure, I will make a new release later today after work :)

**Comment by blazkowolf** [comment]
Thank you!

**Comment by zeroKilo** [comment]
ok, done, have fun
greetz

**Comment by BingoHeelah** [comment]
This release does not appear to work as the project.properties file is the default properties file, and modifying it to match the version still does not allow the plugin to work. Older version releases work just fine on older ghidra versions.

**Comment by zeroKilo** [comment]
I will take a look, but usually I test these before I release them here, so I wonder how this could happen, but will see

**Comment by zeroKilo** [comment]
![image](https://github.com/zeroKilo/N64LoaderWV/assets/12677118/7482d870-305d-4b86-b932-14bd0497d9c6)
![image](https://github.com/zeroKilo/N64LoaderWV/assets/12677118/2aaeffd8-7706-4354-b693-e59c20332bf4)
[XEXLoaderWV.zip](https://github.com/zeroKilo/N64LoaderWV/files/11712739/XEXLoaderWV.zip)
well I tried it and here is the zip im using, im not sure what your problem is

**Comment by ImanCol** [comment]
10.4?

**Comment by zeroKilo** [comment]
> 10.4?

[11.3.1](https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_11.3.1_build)

I will try to update it at the weekend but the next version is 11.3.1, not 10.4
